version: "3.8"

services:
  frontend:
    container_name: docker-booksearch-frontend-c
    image: docker-booksearch-frontend-i
    build: ./kube-books-fe
    ports:
      - 3000:80
  backend:
    container_name: docker-booksearch-backend-c
    image: docker-booksearch-backend-i
    build:
      context: ./kube-books-api
    expose:
      - "9000"
    ports:
      - 9000:9000
    command: ["node", "dist/bin/www"]